/*

 PRESS_START.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 13 x 3
   Tile set      : C:\Users\inder\Documents\GBC\art\font.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 353
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __press_start_h_INCLUDE
#define __press_start_h_INCLUDE
#include <gb/cgb.h>

#define press_start_textWidth 13
#define press_start_textHeight 3
#define press_start_textBank 0

// #define press_start_text press_start_textPLN0
// extern const unsigned char press_start_textPLN0[];
// extern const unsigned char press_start_textPLN1[];
// extern const palette_color_t* const press_start_textCGBPal[];

extern void set_press_start_text_palette(uint8_t start_palette) BANKED;
extern void show_press_start_text(void) BANKED;
extern palette_color_t* get_press_start_palette(uint8_t idx) BANKED;

#endif

/* End of PRESS_START.H */
