/*

 TITLE_BG_TILES_LOW.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 255

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __title_bg_tiles_low_h_INCLUDE
#define __title_bg_tiles_low_h_INCLUDE
#include <gb/cgb.h>

/* Bank of tiles. */
#define title_bg_tiles_lowBank 0

// Palette
// extern const palette_color_t * const title_bg_tiles_lowCGBPal[];

/* Start of tile array. */
// extern const unsigned char title_bg_tiles_low[];

extern void set_title_bg_tiles_low_palette(void) BANKED;
extern void set_title_bg_tiles_low(void) BANKED;
extern palette_color_t* get_title_bg_tiles_low_palette(uint8_t idx) BANKED;

#endif

/* End of TITLE_BG_TILES_LOW.H */
