/*

 TITLE.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\inder\Documents\GBC\art\title_bg.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : Yes
   Block size    : 256

 This file was generated by GBMB v1.8

*/
#ifndef __title_h_INCLUDE
#define __title_h_INCLUDE

#define titleWidth 20
#define titleHeight 18
#define titleBank 0

// #define titleBLK0 titleBLK0PLN0
// extern const unsigned char titleBLK0PLN0[];
// extern const unsigned char titleBLK0PLN1[];
// #define titleBLK1 titleBLK1PLN0
// extern const unsigned char titleBLK1PLN0[];
// extern const unsigned char titleBLK1PLN1[];

extern void set_title_bg_screen(void) BANKED;
extern void hide_press_start_text(void) BANKED;

#endif

/* End of TITLE.H */
