/*

 MINIMAP_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 48

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __minimap_tiles_h_INCLUDE
#define __minimap_tiles_h_INCLUDE
#include <stdint.h>

extern void init_vvvvvv_minimap_tiles(uint8_t start_idx) BANKED;

#endif

/* End of MINIMAP_TILES.H */
