/*

 SPRITE_TILESET_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 23

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __sprite_tileset_tiles_h_INCLUDE
#define __sprite_tileset_tiles_h_INCLUDE

extern void init_vvvvvv_sprite_tiles(void) BANKED;
extern void init_vvvvvv_sprite_palettes(uint8_t pal) BANKED;

#endif

/* End of SPRITE_TILESET_TILES.H */
