/*

 VVVVVV_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 97

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __vvvvvv_tiles_h_INCLUDE
#define __vvvvvv_tiles_h_INCLUDE

void init_vvvvvv_tileset(void) BANKED;

/* Bank of tiles. */
#define vvvvvv_tilesBank 0

/* Start of tile array. */
extern const unsigned char vvvvvv_tiles[];

#endif

/* End of VVVVVV_TILES.H */
