/*

 VVVVVV_MAP.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 140 x 126
   Tile set      : Z:\home\\Documents\GBC\art\VVVVVV\walls_tileset.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __vvvvvv_map_h_INCLUDE
#define __vvvvvv_map_h_INCLUDE

#define vvvvvv_mapWidth 140
#define vvvvvv_mapHeight 126
#define vvvvvv_mapBank 0

extern void set_vvvvvv_map_tile_row(uint8_t row, uint8_t col, uint8_t vram_row) BANKED;
extern void set_vvvvvv_map_tile_row2(uint8_t row, uint8_t col, uint8_t vram_row) BANKED;
extern void set_vvvvvv_map_attrib_row(uint8_t row, uint8_t col, uint8_t vram_row) BANKED;
extern void set_vvvvvv_map_attrib_row2(uint8_t row, uint8_t col, uint8_t vram_row) BANKED;

extern uint8_t get_vvvvvv_map_tile(uint8_t row, uint8_t col) BANKED;
extern uint8_t get_vvvvvv_map_tile2(uint8_t row, uint8_t col) BANKED;
extern uint8_t get_vvvvvv_map_attrib(uint8_t row, uint8_t col) BANKED;
extern uint8_t get_vvvvvv_map_attrib2(uint8_t row, uint8_t col) BANKED;

#define vvvvvv_map vvvvvv_mapPLN0
extern const unsigned char vvvvvv_mapPLN0[];
extern const unsigned char vvvvvv_mapPLN1[];

#endif

/* End of VVVVVV_MAP.H */
