/*

 FISHFORM-BODY_TILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/
#include <gb/gb.h>
// #include <gb/gbdecompress.h>
#include <gb/cgb.h>

#pragma bank 255
BANKREF(fishform_body_tiles)

const palette_color_t* const fishformSpriteCGBPal[] =
{
  /* Gameboy Color palette 0 */
  0,
  8520,
  17038,
  23413,
};

/* Start of tile array. */
const unsigned char fishform_body_tiles[] =
{
  0x00,0x00,0x00,0x00,0x80,0x70,0x34,0xD9,
  0x86,0xFC,0xFA,0xF0,0x00,0x00,0x00,0x00,
  0x34,0x38,0x20,0x3C,0x28,0x34,0x28,0x3C,
  0x20,0x18,0x18,0x10,0x30,0x00,0x00,0x08,
  0x30,0x00,0x48,0x70,0x94,0xE8,0x48,0xF8,
  0x24,0x79,0x3E,0x08,0x0E,0x00,0x00,0x00,
  0x00,0x08,0x06,0x00,0x2E,0x00,0x56,0x3C,
  0xA4,0x58,0x8C,0x78,0x50,0x78,0x20,0x30
};

uint8_t set_fishform_sprite_tiles(uint8_t start_idx) BANKED {
    set_sprite_data(start_idx, 4, fishform_body_tiles);
    return 4;
}

uint8_t set_fishform_sprite_palettes(uint8_t start_idx) BANKED {
    set_sprite_palette(start_idx, 1, fishformSpriteCGBPal);
    return 1;
}

/* End of FISHFORM-BODY_TILES.C */
