/*

 FISHFORM-BODY_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __fishform_body_tiles_h_INCLUDE
#define __fishform_body_tiles_h_INCLUDE

extern uint8_t set_fishform_sprite_tiles(uint8_t start_idx) BANKED;
extern uint8_t set_fishform_sprite_palettes(uint8_t start_idx) BANKED;

#endif

/* End of FISHFORM-BODY_TILES.H */
