/*

 FONT_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 93

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __font_tiles_h_INCLUDE
#define __font_tiles_h_INCLUDE

extern void set_font_tiles(uint8_t start_idx) BANKED;
extern void render_string(uint8_t* str, uint8_t vram_start_idx) BANKED;

#endif

/* End of FONT_TILES.H */
