/*

 FONT_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 93

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __font_tiles_h_INCLUDE
#define __font_tiles_h_INCLUDE

extern void set_font_tiles(uint8_t start_idx) BANKED;
extern int8_t render_next_string_char_id(uint8_t str_id, uint8_t character, uint8_t vram_start_idx) BANKED;
extern void render_textbox_id(uint8_t str_id, uint8_t vram_start_idx) BANKED;

// String IDs
#define TEXT_STRING_TAKEOVER_WORLD  0

#endif

/* End of FONT_TILES.H */
