/*

 FISHFORM_GASP_MAP.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 15 x 9
   Tile set      : fishform_gasp.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __fishform_gasp_map_h_INCLUDE
#define __fishform_gasp_map_h_INCLUDE

extern void draw_fishform_gasp_bg(uint8_t tile_x, uint8_t tile_y) BANKED;

#endif

/* End of FISHFORM_GASP_MAP.H */
