/*

 MIA_BRAINWASH_MAP.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 11 x 12
   Tile set      : mia_brainwash.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __mia_brainwash_map_h_INCLUDE
#define __mia_brainwash_map_h_INCLUDE

extern void draw_mia_brainwash_bg(uint8_t tile_x, uint8_t tile_y) BANKED;

#endif

/* End of MIA_BRAINWASH_MAP.H */
