/*

 MIA_HUG_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 98

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __mia_hug_tiles_h_INCLUDE
#define __mia_hug_tiles_h_INCLUDE

extern void init_mia_hug_tiles(uint8_t tile_start_idx, uint8_t pal_start_idx) BANKED;

#endif

/* End of MIA_HUG_TILES.H */
