/*

 MIA_HUG_MAP.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 9 x 11
   Tile set      : mia_hug.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __mia_hug_map_h_INCLUDE
#define __mia_hug_map_h_INCLUDE

extern void draw_mia_hug_bg(uint8_t tile_x, uint8_t tile_y) BANKED;

#endif

/* End of MIA_HUG_MAP.H */
