/*

 NAIJA_CRYSTAL_MAP.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 11 x 18
   Tile set      : naija_crystal.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __naija_crystal_map_h_INCLUDE
#define __naija_crystal_map_h_INCLUDE

extern void draw_naija_crystal_bg(uint8_t tile_x, uint8_t tile_y) BANKED;

#endif

/* End of NAIJA_CRYSTAL_MAP.H */
