/*

 NAIJA_CRYSTAL_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 175

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __naija_crystal_tiles_h_INCLUDE
#define __naija_crystal_tiles_h_INCLUDE

extern void init_naija_crystal_tiles(uint8_t tile_start_idx, uint8_t pal_start_idx) BANKED;

#endif

/* End of NAIJA_CRYSTAL_TILES.H */
