/*

 SWORDFISH_STEAK_MAP.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 8 x 7
   Tile set      : swordfish_steak.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __swordfish_steak_map_h_INCLUDE
#define __swordfish_steak_map_h_INCLUDE

extern void draw_swordfish_steak_bg(uint8_t tile_x, uint8_t tile_y) BANKED;

#endif

/* End of SWORDFISH_STEAK_MAP.H */
