/*

 MAP1_TILES.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 128 x 100
   Tile set      : C:\Users\inder\Documents\GBC\art\aquaria_bg_tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map1_tiles_h_INCLUDE
#define __map1_tiles_h_INCLUDE

#define map1_tilesWidth 128
#define map1_tilesHeight 100

extern void set_aquaria_map_tiles(void) BANKED;
extern void set_aquaria_map_tile_column(uint8_t col, uint8_t vram_row, uint8_t vram_col) BANKED;
extern void set_aquaria_map_tile_row(uint8_t row, uint8_t vram_row, uint8_t vram_col) BANKED;
extern uint8_t get_aquaria_map_tile(uint8_t row, uint8_t col) BANKED;
BANKREF_EXTERN(map1_tiles)

extern void set_aquaria_map_tile_attribs(void) BANKED;
extern void set_aquaria_map_attrib_column(uint8_t col, uint8_t vram_row, uint8_t vram_col) BANKED;
extern void set_aquaria_map_attrib_row(uint8_t row, uint8_t vram_row, uint8_t vram_col) BANKED;
BANKREF_EXTERN(map1_tileattribs)

#define map1_tiles map1_tilesPLN0
extern const unsigned char map1_tilesPLN0[];
extern const unsigned char map1_tilesPLN1[];

#endif

/* End of MAP1_TILES.H */
