/*

 MAP1_TILES.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 128 x 100
   Tile set      : C:\Users\inder\Documents\GBC\art\aquaria_bg_tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map1_tiles_h_INCLUDE
#define __map1_tiles_h_INCLUDE

#define map1_tilesWidth 128
#define map1_tilesHeight 100
#define map1_tilesBank 0

#define map1_tiles map1_tilesPLN0
extern const unsigned char map1_tilesPLN0[];
extern const unsigned char map1_tilesPLN1[];

#endif

/* End of MAP1_TILES.H */
