/*

 DISCORD_LOGO_MAP.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 20 x 12
   Tile set      : discord_logo.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __discord_logo_map_h_INCLUDE
#define __discord_logo_map_h_INCLUDE

extern void draw_discord_logo_bg(uint8_t tile_x, uint8_t tile_y) BANKED;

#endif

/* End of DISCORD_LOGO_MAP.H */
