/*

 GAME_BY_DAXAR_LOGO_MAP.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 16 x 8
   Tile set      : game_by_daxar_logo.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __game_by_daxar_logo_map_h_INCLUDE
#define __game_by_daxar_logo_map_h_INCLUDE

extern void draw_game_by_daxar_logo_bg(uint8_t tile_x, uint8_t tile_y) BANKED;

#endif

/* End of GAME_BY_DAXAR_LOGO_MAP.H */
