/*

 TITLE_TEXT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 3
   Tile set      : title_bg.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __title_text_h_INCLUDE
#define __title_text_h_INCLUDE

#define title_textWidth 18
#define title_textHeight 3
#define title_textBank 0

#define title_text title_textPLN0
extern const unsigned char title_textPLN0[];
extern const unsigned char title_textPLN1[];

#endif

/* End of TITLE_TEXT.H */
