/*

 TITLE_BG_TILES_HI.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 256 to 352

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __title_bg_tiles_hi_h_INCLUDE
#define __title_bg_tiles_hi_h_INCLUDE

/* Bank of tiles. */
#define title_bg_tiles_hiBank 0

/* Super Gameboy palette 0 */
#define title_bg_tiles_hiSGBPal0c0 0
#define title_bg_tiles_hiSGBPal0c1 0
#define title_bg_tiles_hiSGBPal0c2 0
#define title_bg_tiles_hiSGBPal0c3 0

/* Super Gameboy palette 1 */
#define title_bg_tiles_hiSGBPal1c0 6076
#define title_bg_tiles_hiSGBPal1c1 8935
#define title_bg_tiles_hiSGBPal1c2 6596
#define title_bg_tiles_hiSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define title_bg_tiles_hiSGBPal2c0 6076
#define title_bg_tiles_hiSGBPal2c1 8935
#define title_bg_tiles_hiSGBPal2c2 6596
#define title_bg_tiles_hiSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define title_bg_tiles_hiSGBPal3c0 6076
#define title_bg_tiles_hiSGBPal3c1 8935
#define title_bg_tiles_hiSGBPal3c2 6596
#define title_bg_tiles_hiSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define title_bg_tiles_hiCGBPal0c0 4
#define title_bg_tiles_hiCGBPal0c1 18917
#define title_bg_tiles_hiCGBPal0c2 18218
#define title_bg_tiles_hiCGBPal0c3 32766

/* Gameboy Color palette 1 */
#define title_bg_tiles_hiCGBPal1c0 0
#define title_bg_tiles_hiCGBPal1c1 10398
#define title_bg_tiles_hiCGBPal1c2 29670
#define title_bg_tiles_hiCGBPal1c3 5054

/* Gameboy Color palette 2 */
#define title_bg_tiles_hiCGBPal2c0 0
#define title_bg_tiles_hiCGBPal2c1 0
#define title_bg_tiles_hiCGBPal2c2 0
#define title_bg_tiles_hiCGBPal2c3 0

/* Gameboy Color palette 3 */
#define title_bg_tiles_hiCGBPal3c0 0
#define title_bg_tiles_hiCGBPal3c1 0
#define title_bg_tiles_hiCGBPal3c2 0
#define title_bg_tiles_hiCGBPal3c3 0

/* Gameboy Color palette 4 */
#define title_bg_tiles_hiCGBPal4c0 0
#define title_bg_tiles_hiCGBPal4c1 0
#define title_bg_tiles_hiCGBPal4c2 0
#define title_bg_tiles_hiCGBPal4c3 0

/* Gameboy Color palette 5 */
#define title_bg_tiles_hiCGBPal5c0 0
#define title_bg_tiles_hiCGBPal5c1 0
#define title_bg_tiles_hiCGBPal5c2 0
#define title_bg_tiles_hiCGBPal5c3 0

/* Gameboy Color palette 6 */
#define title_bg_tiles_hiCGBPal6c0 0
#define title_bg_tiles_hiCGBPal6c1 0
#define title_bg_tiles_hiCGBPal6c2 0
#define title_bg_tiles_hiCGBPal6c3 0

/* Gameboy Color palette 7 */
#define title_bg_tiles_hiCGBPal7c0 0
#define title_bg_tiles_hiCGBPal7c1 0
#define title_bg_tiles_hiCGBPal7c2 0
#define title_bg_tiles_hiCGBPal7c3 0
/* Start of tile array. */
extern const unsigned char title_bg_tiles_hi[];

#endif

/* End of TITLE_BG_TILES_HI.H */
