/*

 TITLE_BG_TILES_HI.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 256 to 352

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __title_bg_tiles_hi_h_INCLUDE
#define __title_bg_tiles_hi_h_INCLUDE

/* Bank of tiles. */
#define title_bg_tiles_hiBank 1

/* Start of tile array. */
extern const unsigned char title_bg_tiles_hi[];

#endif

/* End of TITLE_BG_TILES_HI.H */
